
struct Options: Codable {
    let samples_save: Bool?
    let samples_format: String?
    let samples_filename_pattern: String?
    let save_images_add_number: Bool?
    let grid_save: Bool?
    let grid_format: String?
    let grid_extended_filename: Bool?
    let grid_only_if_multiple: Bool?
    let grid_prevent_empty_spots: Bool?
    let grid_zip_filename_pattern: String?
    let n_rows: Double?
    let font: String?
    let grid_text_active_color: String?
    let grid_text_inactive_color: String?
    let grid_background_color: String?
    let enable_pnginfo: Bool?
    let save_txt: Bool?
    let save_images_before_face_restoration: Bool?
    let save_images_before_highres_fix: Bool?
    let save_images_before_color_correction: Bool?
    let save_mask: Bool?
    let save_mask_composite: Bool?
    let jpeg_quality: Double?
    let webp_lossless: Bool?
    let export_for_4chan: Bool?
    let img_downscale_threshold: Double?
    let target_side_length: Double?
    let img_max_size_mp: Double?
    let use_original_name_batch: Bool?
    let use_upscaler_name_as_suffix: Bool?
    let save_selected_only: Bool?
    let save_init_img: Bool?
    let temp_dir: String?
    let clean_temp_dir_at_start: Bool?
    let save_incomplete_images: Bool?
    let outdir_samples: String?
    let outdir_txt2img_samples: String?
    let outdir_img2img_samples: String?
    let outdir_extras_samples: String?
    let outdir_grids: String?
    let outdir_txt2img_grids: String?
    let outdir_img2img_grids: String?
    let outdir_save: String?
    let outdir_init_images: String?
    let save_to_dirs: Bool?
    let grid_save_to_dirs: Bool?
    let use_save_to_dirs_for_ui: Bool?
    let directories_filename_pattern: String?
    let directories_max_prompt_words: Double?
    let esrgan_tile: Int?
    let esrgan_tile_overlap: Double?
    let realesrgan_enabled_models: [String]?
    let upscaler_for_img2img: String??
    let face_restoration: Bool?
    let face_restoration_model: String?
    let code_former_weight: Double?
    let face_restoration_unload: Bool?
    let auto_launch_browser: String?
    let show_warnings: Bool?
    let show_gradio_deprecation_warnings: Bool?
    let memmon_poll_rate: Double?
    let samples_log_stdout: Bool?
    let multiple_tqdm: Bool?
    let print_hypernet_extra: Bool?
    let list_hidden_files: Bool?
    let disable_mmap_load_safetensors: Bool?
    let hide_ldm_prints: Bool?
    let api_enable_requests: Bool?
    let api_forbid_local_requests: Bool?
    let api_useragent: String?
    let unload_models_when_training: Bool?
    let pin_memory: Bool?
    let save_optimizer_state: Bool?
    let save_training_settings_to_txt: Bool?
    let dataset_filename_word_regex: String?
    let dataset_filename_join_string: String?
    let training_image_repeats_per_epoch: Double?
    let training_write_csv_every: Double?
    let training_xattention_optimizations: Bool?
    let training_enable_tensorboard: Bool?
    let training_tensorboard_save_images: Bool?
    let training_tensorboard_flush_every: Double?
    var sd_model_checkpoint: String?
    let sd_checkpoints_limit: Double?
    let sd_checkpoints_keep_in_cpu: Bool?
    let sd_checkpoint_cache: Int?
    let sd_unet: String?
    let enable_quantization: Bool?
    let enable_emphasis: Bool?
    let enable_batch_seeds: Bool?
    let comma_padding_backtrack: Double?
    let clip_stop_at_last_layers: Double?
    let upcast_attn: Bool?
    let tiling: Bool?
    let hires_fix_refiner_pass: String?
    let sdxl_crop_top: Int?
    let sdxl_crop_left: Int?
    let sdxl_refiner_low_aesthetic_score: Double?
    let sdxl_refiner_high_aesthetic_score: Double?
    let sd_vae_explanation: String?
    let sd_vae_checkpoint_cache: Int?
    let sd_vae: String?
    let sd_vae_overrides_per_model_preferences: Bool?
    let auto_vae_precision: Bool?
    let sd_vae_encode_method: String?
    let sd_vae_decode_method: String?
    let inpainting_mask_weight: Double?
    let initial_noise_multiplier: Double?
    let img2img_extra_noise: Double?
    let img2img_color_correction: Bool?
    let img2img_fix_steps: Bool?
    let img2img_background_color: String?
    let img2img_editor_height: Double?
    let img2img_sketch_default_brush_color: String?
    let img2img_inpaint_mask_brush_color: String?
    let img2img_inpaint_sketch_default_brush_color: String?
    let return_mask: Bool?
    let return_mask_composite: Bool?
    let cross_attention_optimization: String?
    let s_min_uncond: Double?
    let token_merging_ratio: Double?
    let token_merging_ratio_img2img: Double?
    let token_merging_ratio_hr: Double?
    let pad_cond_uncond: Bool?
    let persistent_cond_cache: Bool?
    let batch_cond_uncond: Bool?
    let use_old_emphasis_implementation: Bool?
    let use_old_karras_scheduler_sigmas: Bool?
    let no_dpmpp_sde_batch_determinism: Bool?
    let use_old_hires_fix_width_height: Bool?
    let dont_fix_second_order_samplers_schedule: Bool?
    let hires_fix_use_firstpass_conds: Bool?
    let use_old_scheduling: Bool?
    let interrogate_keep_models_in_memory: Bool?
    let interrogate_return_ranks: Bool?
    let interrogate_clip_num_beams: Double?
    let interrogate_clip_min_length: Double?
    let interrogate_clip_max_length: Double?
    let interrogate_clip_dict_limit: Double?
    let interrogate_clip_skip_categories: [String]?
    let interrogate_deepbooru_score_threshold: Double?
    let deepbooru_sort_alpha: Bool?
    let deepbooru_use_spaces: Bool?
    let deepbooru_escape: Bool?
    let deepbooru_filter_tags: String?
    let extra_networks_show_hidden_directories: Bool?
    let extra_networks_hidden_models: String?
    let extra_networks_default_multiplier: Double?
    let extra_networks_card_width: Int?
    let extra_networks_card_height: Int?
    let extra_networks_card_text_scale: Double?
    let extra_networks_card_show_desc: Bool?
    let extra_networks_add_text_separator: String?
    let ui_extra_networks_tab_reorder: String?
    let textual_inversion_print_at_load: Bool?
    let textual_inversion_add_hashes_to_infotext: Bool?
    let sd_hypernetwork: String?
    let localization: String?
    let gradio_theme: String?
    let gradio_themes_cache: Bool?
    let gallery_height: String?
    let return_grid: Bool?
    let do_not_show_images: Bool?
    let send_seed: Bool?
    let send_size: Bool?
    let js_modal_lightbox: Bool?
    let js_modal_lightbox_initially_zoomed: Bool?
    let js_modal_lightbox_gamepad: Bool?
    let js_modal_lightbox_gamepad_repeat: Double?
    let show_progress_in_title: Bool?
    let samplers_in_dropdown: Bool?
    let dimensions_and_batch_together: Bool?
    let keyedit_precision_attention: Double?
    let keyedit_precision_extra: Double?
    let keyedit_delimiters: String?
    let keyedit_move: Bool?
    let quicksettings_list: [String]?
    let ui_tab_order: [String]?
    let hidden_tabs: [String]?
    let ui_reorder_list: [String]?
    let hires_fix_show_sampler: Bool?
    let hires_fix_show_prompts: Bool?
    let disable_token_counters: Bool?
    let add_model_hash_to_info: Bool?
    let add_model_name_to_info: Bool?
    let add_user_name_to_info: Bool?
    let add_version_to_infotext: Bool?
    let disable_weights_auto_swap: Bool?
    let infotext_styles: String?
    let show_progressbar: Bool?
    let live_previews_enable: Bool?
    let live_previews_image_format: String?
    let show_progress_grid: Bool?
    let show_progress_every_n_steps: Double?
    let show_progress_type: String?
    let live_preview_allow_lowvram_full: Bool?
    let live_preview_content: String?
    let live_preview_refresh_period: Double?
    let live_preview_fast_interrupt: Bool?
    let hide_samplers: [String]?
    let eta_ddim: Double?
    let eta_ancestral: Double?
    let ddim_discretize: String?
    let s_churn: Double?
    let s_tmin: Double?
    let s_tmax: Double?
    let s_noise: Double?
    let k_sched_type: String?
    let sigma_min: Double?
    let sigma_max: Double?
    let rho: Double?
    let eta_noise_seed_delta: Int?
    let always_discard_next_to_last_sigma: Bool?
    let sgm_noise_multiplier: Bool?
    let uni_pc_variant: String?
    let uni_pc_skip_type: String?
    let uni_pc_order: Double?
    let uni_pc_lower_order_final: Bool?
    let postprocessing_enable_in_main_ui: [String]?
    let postprocessing_operation_order: [String]?
    let upscaling_max_images_in_cache: Double?
    let disabled_extensions: [String]?
    let disable_all_extensions: String?
    let restore_config_state_file: String?
    let sd_checkpoint_hash: String?

}


